# Generated by Django 3.2.6 on 2021-09-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_covidcontentlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidcontentlink',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
