# Generated by Django 3.2.6 on 2021-09-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_covidcontentlink_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidcontent',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
